from abc import ABC, abstractmethod

class AbstractCompaniaRepository(ABC):
    @abstractmethod
    def get_all(self): ...
    @abstractmethod
    def get_by_id(self, id): ...
    @abstractmethod
    def create(self, data: dict): ...
    @abstractmethod
    def update(self, instance, data: dict): ...
    @abstractmethod
    def delete(self, instance): ...
