from django.db import migrations


def create_usuarios_if_missing(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    existing_tables = schema_editor.connection.introspection.table_names()
    if 'usuarios' in existing_tables:
        return

    schema_editor.execute(
        """
        CREATE TABLE usuarios (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nombre varchar(100) NOT NULL,
            correo varchar(254) NOT NULL UNIQUE,
            password_hash varchar(255) NOT NULL,
            rol varchar(20) NOT NULL,
            fecha_creacion timestamp with time zone NOT NULL DEFAULT now(),
            compania_id bigint NULL REFERENCES companias(id) DEFERRABLE INITIALLY DEFERRED
        );
        """
    )
    schema_editor.execute(
        "CREATE INDEX usuarios_compania_id_idx ON usuarios (compania_id);"
    )


class Migration(migrations.Migration):
    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_usuarios_if_missing, migrations.RunPython.noop),
    ]
