from abc import ABC, abstractmethod

class AbstractUnitOfWork(ABC):
    @abstractmethod
    def __enter__(self): ...
    @abstractmethod
    def __exit__(self, *args): ...
    @abstractmethod
    def commit(self): ...
    @abstractmethod
    def rollback(self): ...
